site_name: Useful Learning Resources for Cognitive Neuroscientists

# Theme configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: pink
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.collapsible
    - toc.integrate
    - search.suggest
    - search.highlight
    - navigation.footer
    - navigation.instant

# Repository information
repo_name: neuro_resources
repo_url: https://github.com/sohaamir/neuro_resources
edit_uri: https://github.com/sohaamir/neuro_resources

# Extra configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sohaamir
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AamirNSohail

# Additional CSS for custom styling
extra_css:
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css

# Additional JavaScript for custom scripts
extra_javascript:
  - js/custom.js

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
      baselevel: 1
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

# Documentation directory
docs_dir: docs

# Navigation structure
nav:
  - Home: index.md
  - Neuroscience Resources: neuro_resources.md
  - NeurOpportunities: neuropportunities.md