site_name: Useful Learning Resources for Cognitive Neuroscientists

# Theme configuration
theme:
  name: mkdocs
  palette:
    primary: indigo
    accent: pink
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  # logo: docs/images/logo.png
  # favicon: docs/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.collapsible
    - toc.integrate
    - search.suggest
    - search.highlight

# Repository information
repo_name: Neuro Resources
repo_url: https://github.com/sohaamir/neuro_resources
edit_uri: blob/main/docs

# Extra configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sohaamir
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AamirNSohail

# Additional CSS for custom styling
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details

# Documentation directory
docs_dir: docs

# Navigation structure
nav:
  - Home: index.md